### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Comment by cjnolet** [comment]
Alan, I think this is ready for review. Do you mind merging this over?

**Comment by eawagner** [comment]
Yeah I will take care of merging it in.

**Comment by cjnolet** [comment]
get a chance to look at thid yet?

**Comment by eawagner** [comment]
Yeah, I am still working on merging in the bug fixes from master in the last release.  I have some changes I want to make and will merge it into master.

**Comment by cjnolet** [comment]
Ok. let me know when ur done and I'll review ur changes too.

**Comment by eawagner** [comment]
No problem.  I am also trying to update recipes at the same time, so it is taking me a little while.

**Comment by cjnolet** [comment]
ok

**Pull request merged**
